
GET http://localhost:3000/peliculas HTTP/1.1

###

GET http://localhost:3000/peliculas/1 HTTP/1.1

###

POST http://localhost:3000/peliculas HTTP/1.1
Content-Type: : application/json

{
    "titulo": "Back to the Future",
    "director": "Maty MCFly",
    "year": 1985,
    "pais": "usa"
}